on:
    push:
      branches:
        - "main"

jobs:
    build_server:
        runs-on: ubuntu-latest
        name: Build Server Container
        steps:
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ vars.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Build and push
                uses: docker/build-push-action@v6
                working-directory: ./NowPlaying
                with:
                    push: true
                    tags: ${{ vars.DOCKERHUB_USERNAME }}/nowplaying-server:latest